name: Build and Deploy Code

on:
  push:
#    we can specify branches, by default all branches
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: test
        run: echo "hello"